-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
--BEGIN;


CREATE TABLE IF NOT EXISTS public."Employees"
(
    emp_id bigserial NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    gender character(1) NOT NULL  CHECK (gender IN ('M','F')),
    address character varying(100),
    email character varying(50),
    depart_id bigint NOT NULL,
    role_id bigint NOT NULL,
    salary_id bigint NOT NULL,
    overtime_id bigint NOT NULL,
    PRIMARY KEY (emp_id)
);

CREATE TABLE IF NOT EXISTS public."Department"
(
    depart_id bigserial NOT NULL,
    depart_name character varying(20),
    depart_city character varying(20),
    PRIMARY KEY (depart_id)
);

CREATE TABLE IF NOT EXISTS public."Roles"
(
    role_id bigserial NOT NULL,
    role character varying(50) NOT NULL,
    PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS public."Salaries"
(
    salary_id bigserial NOT NULL,
    salary_pa numeric(15, 2) NOT NULL,
    PRIMARY KEY (salary_id)
);

CREATE TABLE IF NOT EXISTS public."OvertimeHours"
(
    overtime_id bigserial NOT NULL,
    overtime_hours numeric(10, 2),
    PRIMARY KEY (overtime_id)
);

ALTER TABLE IF EXISTS public."Employees"
    ADD FOREIGN KEY (depart_id)
    REFERENCES public."Department" (depart_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Employees"
    ADD FOREIGN KEY (role_id)
    REFERENCES public."Roles" (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Employees"
    ADD FOREIGN KEY (salary_id)
    REFERENCES public."Salaries" (salary_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Employees"
    ADD FOREIGN KEY (overtime_id)
    REFERENCES public."OvertimeHours" (overtime_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

--INSERTING VALUES INTO THE DEPARTMENTS TABLE

INSERT INTO "Department" (depart_name,depart_city)
VALUES ('Marketing','Johannesburg'),
('Finance','Cape Town'),
('Operations','Johannesburg'),
('HR','Pretoria'),
('Sales','Johanneburg'),
('IT', 'Durban'),
('Research & Dev.','East London'),
('Production','Nelspruit');

SELECT * FROM "Department"

--INSERTING VALUES INTO THE SALARIES TABLE

INSERT INTO "Salaries" (salary_pa)
VALUES (7000.00),
(68000.00),
(12000.00),
(15000.00),
(30000.00),
(72000.00),
(48000.00),
(35000.00);

--INSERTING VALUES INTO THE ROLES TABLE

INSERT INTO "Roles" (role)
VALUES ('Marketing Assistant'),
('Staff Accountant'),
('Operations Analyst'),
('HR Representative'),
('Sales Manager'),
('IT support'),
('Project Manager'),
('Production Manager');

--INSERTING INTO THE OVERTIME HOURS TABLE

INSERT INTO "OvertimeHours" (overtime_hours)
VALUES (3.00),
(2.30),
(2.00), 
(2.00),
(2.40),
(3.00),
(2.45),
(2.45);

--JOINING THE TABLES TO THE MAIN EMPLOYEES TABLE
SELECT
e.first_name,
e.last_name,
e.gender,
e.address,
e.email,
d.depart_name,
r.role,
s.salary_pa,
o.overtime_hours

FROM "Employees" AS e
LEFT JOIN "Department" AS d
ON e.depart_id = d.depart_id
LEFT JOIN "Roles" AS r
ON e.role_id = r.role_id
LEFT JOIN "Salaries" AS s
ON e.salary_id = s.salary_id
LEFT JOIN "OvertimeHours" AS o
ON e.overtime_id = o.overtime_id;

INSERT INTO "Employees" (first_name,last_name,gender,address,email, depart_id,role_id,salary_id,overtime_id)
VALUES ('Joseph','Hart','M','5022 Chopper Street','hartjoseph01@gmail.com',1,1,1,1),
('Angela','Madden','F','478 Pentview Street', 'maddenthebrand@gmail.com',2,2,2,2),
('Solomon','Mahlangu','M','3607 Panel Street','solomonoperations003@yahoo.com',3,3,3,3),
('Lucy','McCarthy','F','2201 OrangeGrove Street', 'theladymccarthy@gmail.com',4,4,4,4),
('Thabang','Mokoena','M','21th Avenue','mokoenasales@salesbulls.co.za',5,5,5,5),
('Amelia','Khoza','F','342 Sunset Avenue','ntombikakhoza@gmail.com',6,6,6,6),
('Aubrey','Mkhize','M','3111 Crystal Street','kwamkhizeofficial@gmail.com',7,7,7,7),
('Natasha','Jones','F','2001 Haddison Street','natashalovesbusiness@gmail.com',8,8,8,8);

SELECT * FROM "Department";
SELECT * FROM "Roles";
SELECT * FROM "Salaries";
SELECT * FROM "OvertimeHours";
SELECT * FROM "Employees";
--END;